version: '2'
services:
  node-master:
    build: .
    networks:
      - webnet
    command: start.sh
    ports:
      - "8081:50700"
      - "8082:8088"
      - "8083:18080"
    depends_on:
      - node1
      - node2
  node1:
    build: .
    networks:
      - webnet
    command: startNodes.sh
  node2:
    build: .
    networks:
      - webnet
    command: startNodes.sh
networks:  
  webnet:
